### ISSUE TITLE
Star emoji

### ISSUE THREAD

**Issue by mattn** [andygrunwald/go-trending#1]
⭐

Hi. (at least, in japanese) I'm guessing many fonts doesn't have glyph of \xE2\xAD\x90.
I suggest to change example code using  ☆ or  ★.

![](http://go-gyazo.appspot.com/f0b01a5d89d954c6.png)

**Comment by andygrunwald** [comment]
Thank you @mattn.
I  didn`t know this. I fixed the examples in the README

**Comment by mattn** [comment]
Thank your.
