### ISSUE TITLE
demos not working

### ISSUE THREAD

**Issue by x0rzkov** [andygrunwald/go-trending#8]
Hi,

Hope you are all well !

I tried the 3 examples in the README, and they all returned no results.

Any reason why ?

Cheers,
X

**Comment by andygrunwald** [comment]
HEy @x0rzkov,
this might be related to an HTML Change from github.com/trending.
The selectors (see https://github.com/andygrunwald/go-trending/blob/master/trending.go#L187) might not work anymore.

Right now, I don't have time to update them (including tests).
If you can do it (+apply a PR), here are some tips:

1. Check out https://github.com/trending
2. Find a unique HTML Selector path for languages + projects
3. CHange this selector paths in the go library here
4. Execute the tests to see a quick result

**Comment by x0rzkov** [comment]
I made a WIP pull request https://github.com/andygrunwald/go-trending/pull/9 but you will have to tidy the rest, is it good for you ?

**Comment by andygrunwald** [comment]
Thanks, let continue the discussion in #9

**Comment by andygrunwald** [comment]
I put a bit of work into this lib. Demo codes in the README are working again (state today).
Feel free to give it a try.
